name: ClientConn Pull Request Action

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'BackOffice/ClientConnection/**'

defaults:
  run:
    working-directory: ./BackOffice/ClientConnection

jobs:
  build:
    runs-on: ubuntu-latest
    container: public.ecr.aws/sam/build-java11

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode verify